name: CI

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          cd deno-server-demo
          ./test.sh


      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: HTTP Test Report
          path: deno-server-demo/reports/report.xml
          reporter: java-junit
  run-test-2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run a multi-line script
        run: |
          cd deno-server-demo
          ./test.sh


      - name: Test Report 222
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: HTTP Test Report 222
          path: deno-server-demo/reports/report.xml
          reporter: java-junit
